import { CompanyInfo } from './companyInfoModel';
import dotenv from 'dotenv';


dotenv.config();

export interface Register {
    custFirstName: string,
    custLastName: string,
    companyName: string,
    mainAccountName: string,
    mainAccountNumber: number,
    salesManID: number,
    custInfoID: number,
    companyInfoID: number,
    mainAccountID: number,
    subAccountName: string,
    subAccountNumber: string,
    pricePlanID: number,
    paymentMethodID: number,
    productTypeID: number,
    contactFirstName: string,
    contactLastName: string,
    subAccountID: number,
    contactPersonTypeID: number,
    contactPersonID: number,
    custMobileNumber: string,
    custMobileTypeID: number,
    companyMobileNumber: string,
    companyMobileTypeID: number,
    pickupMobileNumber: string,
    pickupMobileTypeID: number,
    returnMobileNumber: string,
    returnMobileTypeID: number,
    custEmailTypeID: number,
    custEmail: string,
    companyEmailTypeID: number,
    companyEmail: string,
    pickupEmail: string,
    pickupEmailTypeID: number,
    returnEmail: string,
    returnEmailTypeID: number,
    userName: string,
    webUserPassword: string,
    isEnabled: number,
    salesChannelName: string,
    salesChannelTypeID: number,
    salesChannelURL: string,
    companyAddressTypeID: number,
    companyStreetName: string,
    companyApartmentNumber: number,
    companyFloorNumber: number,
    companyBuildingNumber: number,
    companyCityID: number,
    companyPostalCode: number,
    pickupStreetName: string,
    pickupApartmentNumber: number,
    pickupFloorNumber: number,
    pickupBuildingNumber: number,
    pickupCityID: number,
    pickupPostalCode: number,
    returnStreetName: string,
    returnApartmentNumber: number,
    returnFloorNumber: number,
    returnBuildingNumber: number,
    returnCityID: number,
    returnPostalCode: number,
    pickupLocationName: string,
    returnLocationName: string,
    addressID: number
}